
trigger:
- main

strategy:
  matrix:
    Linux_Python3_09:
      imageName: 'ubuntu-latest'
      python.version: '3.9'
    Linux_Python3_10:
      imageName: 'ubuntu-latest'
      python.version: '3.10'
    Linux_Python3_11:
      imageName: 'ubuntu-latest'
      python.version: '3.11'
    MacOS_Python3_09:
      imageName: 'macOS-latest'
      python.version: '3.9'
    MacOS_Python3_10:
      imageName: 'macOS-latest'
      python.version: '3.10'
    MacOS_Python3_11:
      imageName: 'macOS-latest'
      python.version: '3.11'
    Windows_Python3_09:
      imageName: 'windows-latest'
      python.version: '3.9'
    Windows_Python3_10:
      imageName: 'windows-latest'
      python.version: '3.10'
    Windows_Python3_11:
      imageName: 'windows-latest'
      python.version: '3.11'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    python -m pip install .
  displayName: 'Install ilamb3'

- script: |
    python -m pip install pytest pytest-cov intake-xarray aiohttp
    pytest --cov=ilamb3 -W ignore::RuntimeWarning
  displayName: 'Run tests'
