"""
A list of functions that should be run before myst is started so that all the
content for `literalinclude` is pre-generated. For consistency, keep content
generation for a doc file in a function bearing the file's name.
"""

import importlib
import inspect
import json
import subprocess
import sys
from pathlib import Path

import ilamb3
import pandas as pd
import yaml
from intake_esgf import ESGFCatalog


def api():
    """Generate the API JSON, landing page, and one page per module."""
    docs_dir = Path(__file__).resolve().parent
    fleece = docs_dir / "assets" / "myst-apidoc" / "fleece"
    output = subprocess.check_output(
        [sys.executable, str(fleece), "ilamb3"],
        cwd=docs_dir.parent,
        text=True,
    )
    api_data = json.loads(output)
    generated_dir = docs_dir / "_generated"
    generated_dir.mkdir(exist_ok=True)
    (generated_dir / "ilamb3-api.json").write_text(
        json.dumps(api_data, indent=2) + "\n"
    )

    api_dir = docs_dir / "reference" / "api"
    api_dir.mkdir(exist_ok=True, parents=True)
    modules = sorted(
        name for name, member in api_data.items() if member.get("Kind") != "module"
    )
    for path in api_dir.glob("*.md"):
        path.unlink()

    for module in modules:
        if not module.isidentifier():
            raise ValueError(f"Invalid Python module name: {module!r}")
        (api_dir / f"{module}.md").write_text(f"""---
# Generated by setup_doc_assets.py; do not edit.
title: ilamb3.{module}
---

<!-- myst-apidoc layout v3 -->

:::{{apidoc}} _generated/ilamb3-api.json#{module}
:module: ilamb3
:depth: 1
:layout: rich-fields
:::
""")

    module_links = []
    for module in modules:
        module_links.append(f"- [`ilamb3.{module}`](./{module}.md)")
        for function in sorted(
            name
            for name, member in api_data[module].items()
            if member.get("Kind") != "module"
        ):
            target = f"ilamb3.{module}.{function}"
            module_links.append(f"  - [`{function}`](./{module}.md#{target})")
    module_links = "\n".join(module_links)
    index = f"""---
# Generated by setup_doc_assets.py; do not edit.
title: API Reference
---

The API reference is generated from the public libraries and modules exported by `ilamb3`. These classes and functions can be used by developers to build their own analyses, comparisons, and transforms.

{module_links}
"""
    (api_dir / "index.md").write_text(index)


def basic_genyaml():
    cat = ilamb3.ilamb3_catalog()
    wecann_gpp_key = [key for key in cat.registry if "WECANN" in key and "gpp" in key]
    if len(wecann_gpp_key) != 1:
        raise ValueError(f"Ambiguity in finding WECANN gpp {wecann_gpp_key=}")
    wecann_gpp_key = wecann_gpp_key[0]
    out = {
        "Ecosystem and Carbon Cycle": {
            "Gross Primary Productivity": {
                "WECANN-1-0": {
                    "sources": {"gpp": wecann_gpp_key},
                    "variable_cmap": "Greens",
                }
            }
        }
    }
    with open("_generated/my_benchmark_study.yaml", "w") as f:
        f.write(yaml.dump(out))
    cat.fetch(wecann_gpp_key)


def basic_canesm5():
    KEY_PATTERN = [
        "mip_era",
        "activity_id",
        "institution_id",
        "source_id",
        "experiment_id",
        "member_id",
        "table_id",
        "variable_id",
        "grid_label",
    ]
    cat = (
        ESGFCatalog()
        .search(
            experiment_id="historical",
            source_id="CanESM5",
            variable_id=["gpp", "areacella", "sftlf"],
            frequency=["mon", "fx"],
            file_start="1980-01",
            file_end="2016-01",
        )
        .remove_ensembles()
    )
    dpd = cat.to_path_dict(minimal_keys=False)
    df = []
    for key, paths in dpd.items():
        row = {col: value for col, value in zip(KEY_PATTERN, key.split("."))}
        for path in paths:
            row["path"] = str(path)
            df.append(row)
    df = pd.DataFrame(df)
    df.to_csv("_generated/CanESM5.csv")


def datasets_ilamb3():
    cat = ilamb3.ilamb3_catalog()
    df = (
        pd.DataFrame(
            [
                {
                    "source_id": key.split("/")[0],
                    "variable_id": key.split("/")[1].split("_")[4],
                    "key": key,
                    # "download": f"<a href='{cat.get_url(key)}'>'⤓'</a>",
                }
                for key in cat.registry
            ]
        )
        .sort_values(["source_id", "variable_id"])
        .set_index(["source_id", "variable_id"])
    )
    styles = [
        {"selector": "th.col0, td.col0", "props": [("width", "5%")]},
        {"selector": "th.col1, td.col1", "props": [("width", "5%")]},
        {"selector": "th.col2, td.col2", "props": [("width", "90%")]},
    ]
    with open("_generated/catalog_ilamb3.html", "w") as fout:
        fout.write(df.style.set_table_styles(styles).to_html())


def datasets_ilamb():
    cat = ilamb3.ilamb_catalog()
    df = (
        pd.DataFrame(
            [
                {
                    "source_id": key.split("/")[1],
                    "variable_id": key.split("/")[0],
                    "key": key,
                }
                for key in cat.registry
                if not (key.startswith("test") or "regions" in key)
            ]
        )
        .sort_values(["source_id", "variable_id"])
        .set_index(["source_id", "variable_id"])
    )
    styles = [
        {"selector": "th.col0, td.col0", "props": [("width", "5%")]},
        {"selector": "th.col1, td.col1", "props": [("width", "5%")]},
        {"selector": "th.col2, td.col2", "props": [("width", "90%")]},
    ]
    with open("_generated/catalog_ilamb.html", "w") as fout:
        fout.write(df.style.set_table_styles(styles).to_html())


def datasets_iomb():
    cat = ilamb3.iomb_catalog()
    df = (
        pd.DataFrame(
            [
                {
                    "source_id": key.split("/")[0],
                    "key": key,
                }
                for key in cat.registry
            ]
        )
        .sort_values(["source_id"])
        .set_index(["source_id"])
    )
    styles = [
        {"selector": "th.col0, td.col0", "props": [("width", "5%")]},
        {"selector": "th.col1, td.col1", "props": [("width", "90%")]},
    ]
    with open("_generated/catalog_iomb.html", "w") as fout:
        fout.write(df.style.set_table_styles(styles).to_html())

def analysis_genyaml():
    cat = ilamb3.ilamb3_catalog()
    wecann_gpp_key = [key for key in cat.registry if "WECANN" in key and "gpp" in key]
    if len(wecann_gpp_key) != 1:
        raise ValueError(f"Ambiguity in finding WECANN gpp {wecann_gpp_key=}")
    wecann_gpp_key = wecann_gpp_key[0]
    out = {
        "WECANN-1-0": {
            "sources": {"gpp": wecann_gpp_key},
            "variable_cmap": "Greens",
            "analyses": ["absrelerror"]
        }
    }
    with open("_generated/my_analysis_test.yaml", "w") as f:
        f.write(yaml.dump(out))
    cat.fetch(wecann_gpp_key)

if __name__ == "__main__":
    Path("_generated").mkdir(exist_ok=True, parents=True)
    mod = importlib.import_module("setup_doc_assets")
    for _, fnc in inspect.getmembers(mod, inspect.isfunction):
        fnc()
